import './App.css'

function App() {
  return (
    <>
    <header className="site-header">
      <nav className="navbar" aria-label="Navegação principal">
        <a className="brand" href="#inicio" aria-label="Nuvem, início">
          <span className="brand-mark" aria-hidden="true">N</span>
          <span>Nuvem</span>
        </a>

        <div className="nav-links">
          <a className="active" href="#inicio">Início</a>
          <a href="#servicos">Serviços</a>
          <a href="#sobre">Sobre nós</a>
          <a href="#blog">Blog</a>
        </div>
                 
        <a className="nav-cta" href="#contato">Fale conosco <span aria-hidden="true">↗</span></a>
      </nav>
    </header>
   <p className="screen-message">
     <span className="screen-message__cellphone">Tela detectada: celular</span>
     <span className="screen-message__tablet">Tela detectada: tablet</span>
     <span className="screen-message__pc">Tela detectada: PC</span>
   </p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
   <p>teste</p>
    </>
  )
}

export default App
